In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
url='https://raw.githubusercontent.com/anantdivanji/LearnDigital-/main/4th%20Sem/loan_Feb.csv'

In [3]:
data=pd.read_csv(url)
data.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,NaN,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y

In [4]:
data.shape

(614, 13)

In [5]:
data.isnull().sum()

Loan_ID               0
Gender               13
Married               3
Dependents           15
Education             0
Self_Employed        32
ApplicantIncome       0
CoapplicantIncome     0
LoanAmount           22
Loan_Amount_Term     14
Credit_History       50
Property_Area         0
Loan_Status           0
dtype: int64

In [6]:
data.isnull().sum()/len(data) *100

Loan_ID              0.000000
Gender               2.117264
Married              0.488599
Dependents           2.442997
Education            0.000000
Self_Employed        5.211726
ApplicantIncome      0.000000
CoapplicantIncome    0.000000
LoanAmount           3.583062
Loan_Amount_Term     2.280130
Credit_History       8.143322
Property_Area        0.000000
Loan_Status          0.000000
dtype: float64

## Observation
1. Gender,Self_Employed and Married are text columns having missing values.
2. Dependents,LoanAmount ,Loan_Amount_Term and Credit_History are the numerical columns having missing values.

In [7]:
from sklearn.impute import SimpleImputer
si=SimpleImputer(strategy='median')
si

SimpleImputer(strategy='median')

In [8]:
data['LoanAmount']=si.fit_transform(data[['LoanAmount']])
data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [9]:
from sklearn.impute import SimpleImputer
si=SimpleImputer(strategy='most_frequent')
si

SimpleImputer(strategy='most_frequent')

In [10]:
data[['Gender','Self_Employed','Married','Dependents','Loan_Amount_Term','Credit_History']]=si.fit_transform(data[['Gender','Self_Employed','Married','Dependents','Loan_Amount_Term','Credit_History']])
data

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,5849,0.0,128.0,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,4583,1508.0,128.0,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,3000,0.0,66.0,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,2583,2358.0,120.0,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,6000,0.0,141.0,360.0,1.0,Urban,Y
...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,LP002978,Female,No,0,Graduate,No,2900,0.0,71.0,360.0,1.0,Rural,Y
610,LP002979,Male,Yes,3+,Graduate,No,4106,0.0,40.0,180.0,1.0,Rural,Y
611,LP002983,Male,Yes,1,Graduate,No,8072,240.0,253.0,360.0,1.0,Urban,Y
612,LP002984,Male,Yes,2,Graduate,No,7583,0.0,187.0,360.0,1.0,Urban,Y
613,LP002990,Female,No,0,Graduate,Yes,4583,0.0,133.0,360.0,0.0,Semiurban,N

In [11]:
data.isnull().sum()

Loan_ID              0
Gender               0
Married              0
Dependents           0
Education            0
Self_Employed        0
ApplicantIncome      0
CoapplicantIncome    0
LoanAmount           0
Loan_Amount_Term     0
Credit_History       0
Property_Area        0
Loan_Status          0
dtype: int64

## Feature Scaling

In [12]:
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler()
mms

MinMaxScaler()

In [13]:
data[['ApplicantIncome','CoapplicantIncome','LoanAmount']] = mms.fit_transform(data[['ApplicantIncome','CoapplicantIncome','LoanAmount']] )

In [14]:
data.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,Male,No,0,Graduate,No,0.070489,0.000000,0.172214,360.0,1.0,Urban,Y
1,LP001003,Male,Yes,1,Graduate,No,0.054830,0.036192,0.172214,360.0,1.0,Rural,N
2,LP001005,Male,Yes,0,Graduate,Yes,0.035250,0.000000,0.082489,360.0,1.0,Urban,Y
3,LP001006,Male,Yes,0,Not Graduate,No,0.030093,0.056592,0.160637,360.0,1.0,Urban,Y
4,LP001008,Male,No,0,Graduate,No,0.072356,0.000000,0.191027,360.0,1.0,Urban,Y

### Feature Encoding

In [15]:
dic1={
    'Male':0,
    'Female':1
}

dic2={
    'Yes':1,
    'No':0
}

dic3={
    'Not Graduate':0,
    'Graduate':1
}

dic4={
    'Y':1,
    'N':0
}

In [16]:
data[['Married','Self_Employed']]=data[['Married','Self_Employed']].replace(dic2)
data['Gender']=data['Gender'].replace(dic1)
data['Education']=data['Education'].replace(dic3)
data['Loan_Status']=data['Loan_Status'].replace(dic4)

In [17]:
data.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,LP001002,0,0,0,1,0,0.070489,0.000000,0.172214,360.0,1.0,Urban,1
1,LP001003,0,1,1,1,0,0.054830,0.036192,0.172214,360.0,1.0,Rural,0
2,LP001005,0,1,0,1,1,0.035250,0.000000,0.082489,360.0,1.0,Urban,1
3,LP001006,0,1,0,0,0,0.030093,0.056592,0.160637,360.0,1.0,Urban,1
4,LP001008,0,0,0,1,0,0.072356,0.000000,0.191027,360.0,1.0,Urban,1

In [18]:
data=data.drop(columns='Loan_ID')
data

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status
0,0,0,0,1,0,0.070489,0.000000,0.172214,360.0,1.0,Urban,1
1,0,1,1,1,0,0.054830,0.036192,0.172214,360.0,1.0,Rural,0
2,0,1,0,1,1,0.035250,0.000000,0.082489,360.0,1.0,Urban,1
3,0,1,0,0,0,0.030093,0.056592,0.160637,360.0,1.0,Urban,1
4,0,0,0,1,0,0.072356,0.000000,0.191027,360.0,1.0,Urban,1
...,...,...,...,...,...,...,...,...,...,...,...,...
609,1,0,0,1,0,0.034014,0.000000,0.089725,360.0,1.0,Rural,1
610,0,1,3+,1,0,0.048930,0.000000,0.044863,180.0,1.0,Rural,1
611,0,1,1,1,0,0.097984,0.005760,0.353111,360.0,1.0,Urban,1
612,0,1,2,1,0,0.091936,0.000000,0.257598,360.0,1.0,Urban,1
613,1,0,0,1,1,0.054830,0.000000,0.179450,360.0,0.0,Semiurban,0

In [19]:
data_ohe=pd.get_dummies(data['Property_Area'],dtype='int')
data_ohe

     Rural  Semiurban  Urban
0        0          0      1
1        1          0      0
2        0          0      1
3        0          0      1
4        0          0      1
..     ...        ...    ...
609      1          0      0
610      1          0      0
611      0          0      1
612      0          0      1
613      0          1      0

[614 rows x 3 columns]

In [20]:
data=pd.concat([data,data_ohe],axis=1)
data

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Loan_Status,Rural,Semiurban,Urban
0,0,0,0,1,0,0.070489,0.000000,0.172214,360.0,1.0,Urban,1,0,0,1
1,0,1,1,1,0,0.054830,0.036192,0.172214,360.0,1.0,Rural,0,1,0,0
2,0,1,0,1,1,0.035250,0.000000,0.082489,360.0,1.0,Urban,1,0,0,1
3,0,1,0,0,0,0.030093,0.056592,0.160637,360.0,1.0,Urban,1,0,0,1
4,0,0,0,1,0,0.072356,0.000000,0.191027,360.0,1.0,Urban,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,1,0,0,1,0,0.034014,0.000000,0.089725,360.0,1.0,Rural,1,1,0,0
610,0,1,3+,1,0,0.048930,0.000000,0.044863,180.0,1.0,Rural,1,1,0,0
611,0,1,1,1,0,0.097984,0.005760,0.353111,360.0,1.0,Urban,1,0,0,1
612,0,1,2,1,0,0.091936,0.000000,0.257598,360.0,1.0,Urban,1,0,0,1
613,1,0,0,1,1,0.054830,0.000000,0.179450,360.0,0.0,Semiurban,0,0,1,0

In [21]:
data=data.drop(columns='Property_Area')
data

,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Loan_Status,Rural,Semiurban,Urban
0,0,0,0,1,0,0.070489,0.000000,0.172214,360.0,1.0,1,0,0,1
1,0,1,1,1,0,0.054830,0.036192,0.172214,360.0,1.0,0,1,0,0
2,0,1,0,1,1,0.035250,0.000000,0.082489,360.0,1.0,1,0,0,1
3,0,1,0,0,0,0.030093,0.056592,0.160637,360.0,1.0,1,0,0,1
4,0,0,0,1,0,0.072356,0.000000,0.191027,360.0,1.0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
609,1,0,0,1,0,0.034014,0.000000,0.089725,360.0,1.0,1,1,0,0
610,0,1,3+,1,0,0.048930,0.000000,0.044863,180.0,1.0,1,1,0,0
611,0,1,1,1,0,0.097984,0.005760,0.353111,360.0,1.0,1,0,0,1
612,0,1,2,1,0,0.091936,0.000000,0.257598,360.0,1.0,1,0,0,1
613,1,0,0,1,1,0.054830,0.000000,0.179450,360.0,0.0,0,0,1,0

## automating all the above steps performed using pipeline() from the sklearn library
1. import all the libraries and functions for performing data processing
2. mention the steps needed to perform automation and store all the steps in the 'steps' variable
3. import pipeline() from sklearn library and create a pipeline with 'steps' variable

### step 1

In [22]:
from sklearn.impute import SimpleImputer
si=SimpleImputer(strategy='median')
si

SimpleImputer(strategy='median')

In [23]:
from sklearn.preprocessing import MinMaxScaler
mms=MinMaxScaler()
mms

MinMaxScaler()

## step 2

In [24]:
num_steps=[('num missing treatments',si),('num_scaling',mms)]
num_steps

[('num missing treatments', SimpleImputer(strategy='median')),
 ('num_scaling', MinMaxScaler())]

## step 3

In [25]:
from sklearn.pipeline import Pipeline
num_pipe=Pipeline(num_steps)
num_pipe

Pipeline(steps=[('num missing treatments', SimpleImputer(strategy='median')),
                ('num_scaling', MinMaxScaler())])

In [39]:
dt_mar=pd.read_csv('https://raw.githubusercontent.com/anantdivanji/LearnDigital-/main/4th%20Sem/loan_March.csv')
dt_mar.head()

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,5720,0,110.0,360.0,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,3076,1500,126.0,360.0,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,5000,1800,208.0,360.0,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,2340,2546,100.0,360.0,NaN,Urban
4,LP001051,Male,No,0,Not Graduate,No,3276,0,78.0,360.0,1.0,Urban

In [27]:
dt_mar[['ApplicantIncome','CoapplicantIncome','LoanAmount']]=num_pipe.fit_transform(dt_mar[['ApplicantIncome','CoapplicantIncome','LoanAmount']])
dt_mar

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area
0,LP001015,Male,Yes,0,Graduate,No,0.078865,0.000000,0.157088,360.0,1.0,Urban
1,LP001022,Male,Yes,1,Graduate,No,0.042411,0.062500,0.187739,360.0,1.0,Urban
2,LP001031,Male,Yes,2,Graduate,No,0.068938,0.075000,0.344828,360.0,1.0,Urban
3,LP001035,Male,Yes,2,Graduate,No,0.032263,0.106083,0.137931,360.0,NaN,Urban
4,LP001051,Male,No,0,Not Graduate,No,0.045168,0.000000,0.095785,360.0,1.0,Urban
...,...,...,...,...,...,...,...,...,...,...,...,...
362,LP002971,Male,Yes,3+,Not Graduate,Yes,0.055274,0.074042,0.162835,360.0,1.0,Urban
363,LP002975,Male,Yes,0,Graduate,No,0.057329,0.029542,0.166667,360.0,1.0,Urban
364,LP002980,Male,No,0,Graduate,No,0.044810,0.083042,0.187739,360.0,NaN,Semiurban
365,LP002986,Male,Yes,0,Graduate,No,0.068938,0.099708,0.249042,360.0,1.0,Rural
366,LP002989,Male,No,0,Graduate,Yes,0.126846,0.000000,0.134100,180.0,1.0,Rural

## create the pipeline for the categorical data

### step 1

In [28]:
from sklearn.impute import SimpleImputer
si_text=SimpleImputer(strategy='most_frequent')
si_text

SimpleImputer(strategy='most_frequent')

In [29]:
from sklearn.preprocessing import OneHotEncoder
ohe=OneHotEncoder()
ohe

OneHotEncoder()

# step 2

## skipped

# step 3

In [30]:
from sklearn.pipeline import make_pipeline
cat_pipe=make_pipeline(si_text,ohe)
cat_pipe

Pipeline(steps=[('simpleimputer', SimpleImputer(strategy='most_frequent')),
                ('onehotencoder', OneHotEncoder())])

## Apply cat_pipe on loan_march data

In [31]:
data_cat_pipe=cat_pipe.fit_transform(dt_mar[['Property_Area']])
data_cat_pipe

<367x3 sparse matrix of type '<class 'numpy.float64'>'
	with 367 stored elements in Compressed Sparse Row format>

In [32]:
data_cat_pipe.toarray()

array([[0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       ...,
       [0., 1., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [33]:
data_ohe=pd.DataFrame(data_cat_pipe.toarray(),columns=['Rural','Urban','Semiurban'])
data_ohe

     Rural  Urban  Semiurban
0      0.0    0.0        1.0
1      0.0    0.0        1.0
2      0.0    0.0        1.0
3      0.0    0.0        1.0
4      0.0    0.0        1.0
..     ...    ...        ...
362    0.0    0.0        1.0
363    0.0    0.0        1.0
364    0.0    1.0        0.0
365    1.0    0.0        0.0
366    1.0    0.0        0.0

[367 rows x 3 columns]

In [34]:
dt_mar=pd.concat([dt_mar,data_ohe],axis=1)
dt_mar

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Property_Area,Rural,Urban,Semiurban
0,LP001015,Male,Yes,0,Graduate,No,0.078865,0.000000,0.157088,360.0,1.0,Urban,0.0,0.0,1.0
1,LP001022,Male,Yes,1,Graduate,No,0.042411,0.062500,0.187739,360.0,1.0,Urban,0.0,0.0,1.0
2,LP001031,Male,Yes,2,Graduate,No,0.068938,0.075000,0.344828,360.0,1.0,Urban,0.0,0.0,1.0
3,LP001035,Male,Yes,2,Graduate,No,0.032263,0.106083,0.137931,360.0,NaN,Urban,0.0,0.0,1.0
4,LP001051,Male,No,0,Not Graduate,No,0.045168,0.000000,0.095785,360.0,1.0,Urban,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362,LP002971,Male,Yes,3+,Not Graduate,Yes,0.055274,0.074042,0.162835,360.0,1.0,Urban,0.0,0.0,1.0
363,LP002975,Male,Yes,0,Graduate,No,0.057329,0.029542,0.166667,360.0,1.0,Urban,0.0,0.0,1.0
364,LP002980,Male,No,0,Graduate,No,0.044810,0.083042,0.187739,360.0,NaN,Semiurban,0.0,1.0,0.0
365,LP002986,Male,Yes,0,Graduate,No,0.068938,0.099708,0.249042,360.0,1.0,Rural,1.0,0.0,0.0
366,LP002989,Male,No,0,Graduate,Yes,0.126846,0.000000,0.134100,180.0,1.0,Rural,1.0,0.0,0.0

In [35]:
dt_mar=dt_mar.drop(columns='Property_Area')
dt_mar

,Loan_ID,Gender,Married,Dependents,Education,Self_Employed,ApplicantIncome,CoapplicantIncome,LoanAmount,Loan_Amount_Term,Credit_History,Rural,Urban,Semiurban
0,LP001015,Male,Yes,0,Graduate,No,0.078865,0.000000,0.157088,360.0,1.0,0.0,0.0,1.0
1,LP001022,Male,Yes,1,Graduate,No,0.042411,0.062500,0.187739,360.0,1.0,0.0,0.0,1.0
2,LP001031,Male,Yes,2,Graduate,No,0.068938,0.075000,0.344828,360.0,1.0,0.0,0.0,1.0
3,LP001035,Male,Yes,2,Graduate,No,0.032263,0.106083,0.137931,360.0,NaN,0.0,0.0,1.0
4,LP001051,Male,No,0,Not Graduate,No,0.045168,0.000000,0.095785,360.0,1.0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
362,LP002971,Male,Yes,3+,Not Graduate,Yes,0.055274,0.074042,0.162835,360.0,1.0,0.0,0.0,1.0
363,LP002975,Male,Yes,0,Graduate,No,0.057329,0.029542,0.166667,360.0,1.0,0.0,0.0,1.0
364,LP002980,Male,No,0,Graduate,No,0.044810,0.083042,0.187739,360.0,NaN,0.0,1.0,0.0
365,LP002986,Male,Yes,0,Graduate,No,0.068938,0.099708,0.249042,360.0,1.0,1.0,0.0,0.0
366,LP002989,Male,No,0,Graduate,Yes,0.126846,0.000000,0.134100,180.0,1.0,1.0,0.0,0.0

## create a column transform function to automate numerical and categorical pipeline
1. create separate all numerical and categorical variables
2. create a column transform() using sklearn library
3. apply the transformer on the data

# step 1

In [36]:
num_features=['ApplicantIncome','CoapplicantIncome','LoanAmount']
cat_features=['Property_Area']

# step 2

In [37]:
from sklearn.compose import ColumnTransformer
col_trans=ColumnTransformer(
                [
                    ('numerical_pipeline',num_pipe,num_features),
                    ('categorical_pipeline',cat_pipe,cat_features)
                ]
)
col_trans

ColumnTransformer(transformers=[('numerical_pipeline',
                                 Pipeline(steps=[('num missing treatments',
                                                  SimpleImputer(strategy='median')),
                                                 ('num_scaling',
                                                  MinMaxScaler())]),
                                 ['ApplicantIncome', 'CoapplicantIncome',
                                  'LoanAmount']),
                                ('categorical_pipeline',
                                 Pipeline(steps=[('simpleimputer',
                                                  SimpleImputer(strategy='most_frequent')),
                                                 ('onehotencoder',
                                                  OneHotEncoder())]),
                                 ['Property_Area'])])

# step 3

In [41]:
data_col_trans=col_trans.fit_transform(dt_mar)

In [42]:
data_col_trans

array([[0.07886501, 0.        , 0.15708812, 0.        , 0.        ,
        1.        ],
       [0.04241062, 0.0625    , 0.18773946, 0.        , 0.        ,
        1.        ],
       [0.06893794, 0.075     , 0.34482759, 0.        , 0.        ,
        1.        ],
       ...,
       [0.04480966, 0.08304167, 0.18773946, 0.        , 1.        ,
        0.        ],
       [0.06893794, 0.09970833, 0.24904215, 1.        , 0.        ,
        0.        ],
       [0.12684581, 0.        , 0.13409962, 1.        , 0.        ,
        0.        ]])