In [41]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [5]:
path=r"C:\Users\Ranjitha\Downloads\Student_perf.csv"

In [7]:
data=pd.read_csv(path)
data

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,19.833723,7,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,15.408756,0,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,4.210570,26,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,10.028829,14,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,4.672495,17,1,3,0,0,0,0,1.288061,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,3388,18,1,0,3,10.680555,2,0,4,1,0,0,0,3.455509,0.0
2388,3389,17,0,0,1,7.583217,4,1,4,0,1,0,0,3.279150,4.0
2389,3390,16,1,0,2,6.805500,20,0,2,0,0,0,1,1.142333,2.0
2390,3391,16,1,1,0,12.416653,17,0,2,0,1,1,0,1.803297,1.0
2391,3392,16,1,0,2,17.819907,13,0,2,0,0,0,1,2.140014,1.0

In [9]:
data.isnull().sum()

StudentID            0
Age                  0
Gender               0
Ethnicity            0
ParentalEducation    0
StudyTimeWeekly      0
Absences             0
Tutoring             0
ParentalSupport      0
Extracurricular      0
Sports               0
Music                0
Volunteering         0
GPA                  0
GradeClass           0
dtype: int64

In [13]:
from sklearn.preprocessing import RobustScaler
RS=RobustScaler()
RS

RobustScaler()

In [15]:
data.describe()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
count,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000,2392.000000
mean,2196.500000,16.468645,0.510870,0.877508,1.746237,9.771992,14.541388,0.301421,2.122074,0.383361,0.303512,0.196906,0.157191,1.906186,2.983696
std,690.655244,1.123798,0.499986,1.028476,1.000411,5.652774,8.467417,0.458971,1.122813,0.486307,0.459870,0.397744,0.364057,0.915156,1.233908
min,1001.000000,15.000000,0.000000,0.000000,0.000000,0.001057,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,1598.750000,15.000000,0.000000,0.000000,1.000000,5.043079,7.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.174803,2.000000
50%,2196.500000,16.000000,1.000000,0.000000,2.000000,9.705363,15.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,1.893393,4.000000
75%,2794.250000,17.000000,1.000000,2.000000,2.000000,14.408410,22.000000,1.000000,3.000000,1.000000,1.000000,0.000000,0.000000,2.622216,4.000000
max,3392.000000,18.000000,1.000000,3.000000,4.000000,19.978094,29.000000,1.000000,4.000000,1.000000,1.000000,1.000000,1.000000,4.000000,4.000000

In [17]:
data[['StudyTimeWeekly','Absences']]=RS.fit_transform(data[['StudyTimeWeekly','Absences']])
data.head()

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA,GradeClass
0,1001,17,1,0,2,1.081474,-0.533333,1,2,0,0,1,0,2.929196,2.0
1,1002,18,0,0,1,0.608990,-1.000000,0,1,0,0,0,0,3.042915,1.0
2,1003,15,0,2,3,-0.586716,0.733333,0,2,0,0,0,0,0.112602,4.0
3,1004,17,1,0,3,0.034539,-0.066667,0,3,1,0,0,0,2.054218,3.0
4,1005,17,1,0,2,-0.537394,0.133333,1,3,0,0,0,0,1.288061,4.0

In [19]:
X=data.drop(columns='GradeClass')
X

,StudentID,Age,Gender,Ethnicity,ParentalEducation,StudyTimeWeekly,Absences,Tutoring,ParentalSupport,Extracurricular,Sports,Music,Volunteering,GPA
0,1001,17,1,0,2,1.081474,-0.533333,1,2,0,0,1,0,2.929196
1,1002,18,0,0,1,0.608990,-1.000000,0,1,0,0,0,0,3.042915
2,1003,15,0,2,3,-0.586716,0.733333,0,2,0,0,0,0,0.112602
3,1004,17,1,0,3,0.034539,-0.066667,0,3,1,0,0,0,2.054218
4,1005,17,1,0,2,-0.537394,0.133333,1,3,0,0,0,0,1.288061
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2387,3388,18,1,0,3,0.104128,-0.866667,0,4,1,0,0,0,3.455509
2388,3389,17,0,0,1,-0.226596,-0.733333,1,4,0,1,0,0,3.279150
2389,3390,16,1,0,2,-0.309638,0.333333,0,2,0,0,0,1,1.142333
2390,3391,16,1,1,0,0.289503,0.133333,0,2,0,1,1,0,1.803297
2391,3392,16,1,0,2,0.866445,-0.133333,0,2,0,0,0,1,2.140014

In [23]:
y=data['GradeClass']
y

0       2.0
1       1.0
2       4.0
3       3.0
4       4.0
       ...
2387    0.0
2388    4.0
2389    2.0
2390    1.0
2391    1.0
Name: GradeClass, Length: 2392, dtype: float64

In [29]:
from sklearn.model_selection import train_test_split

In [84]:
X_train,X_test,y_train,y_test=train_test_split(X,y,random_state=1,test_size=0.25)

In [86]:
from sklearn.linear_model import LogisticRegression
lst=LogisticRegression()
lst

LogisticRegression()

In [88]:
lst.fit(X_train,y_train)

LogisticRegression()

In [89]:
y_pred=lst.predict(X_test)
y_pred

array([2., 4., 4., 4., 2., 4., 4., 3., 2., 4., 3., 1., 3., 3., 4., 4., 0.,
       4., 4., 4., 1., 0., 4., 4., 0., 4., 4., 4., 2., 4., 2., 4., 2., 4.,
       3., 4., 3., 2., 4., 4., 4., 4., 3., 4., 4., 3., 4., 4., 4., 4., 3.,
       1., 4., 4., 4., 2., 4., 4., 4., 4., 4., 4., 1., 4., 4., 4., 4., 4.,
       2., 4., 4., 4., 4., 2., 4., 4., 4., 4., 3., 2., 4., 3., 2., 2., 4.,
       4., 2., 2., 2., 2., 4., 3., 4., 2., 2., 4., 4., 4., 4., 0., 2., 4.,
       4., 4., 4., 3., 4., 2., 4., 4., 4., 2., 3., 4., 4., 4., 2., 4., 4.,
       4., 4., 1., 4., 4., 2., 4., 4., 4., 4., 4., 2., 2., 4., 4., 4., 2.,
       4., 0., 4., 4., 4., 4., 4., 0., 2., 4., 4., 4., 4., 4., 2., 4., 2.,
       4., 4., 2., 4., 4., 0., 4., 4., 2., 3., 4., 4., 4., 2., 4., 4., 4.,
       2., 4., 4., 4., 4., 4., 4., 2., 3., 3., 4., 3., 4., 4., 4., 4., 4.,
       2., 4., 4., 3., 2., 4., 4., 2., 4., 4., 4., 2., 4., 3., 4., 1., 3.,
       3., 2., 0., 4., 4., 2., 2., 4., 0., 4., 2., 4., 4., 4., 2., 3., 2.,
       4., 4., 3., 4., 4., 2., 1., 4., 1., 3., 2., 4., 2., 3., 2., 4., 4.,
       3., 2., 2., 2., 4., 4., 2., 4., 4., 4., 4., 4., 4., 3., 3., 0., 4.,
       4., 4., 3., 4., 4., 4., 4., 4., 4., 4., 1., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 4., 4., 4., 4., 2., 4., 4., 4., 2., 4., 4., 3., 4., 4.,
       4., 4., 4., 2., 4., 4., 0., 4., 4., 4., 2., 2., 4., 4., 2., 4., 2.,
       2., 3., 4., 2., 4., 4., 2., 4., 4., 2., 4., 4., 4., 4., 4., 4., 4.,
       4., 4., 4., 2., 2., 4., 4., 4., 4., 2., 3., 4., 4., 2., 4., 4., 4.,
       2., 4., 4., 4., 2., 4., 4., 4., 4., 4., 2., 4., 0., 4., 4., 0., 2.,
       4., 2., 3., 4., 4., 4., 3., 4., 1., 4., 4., 4., 4., 4., 4., 4., 3.,
       4., 4., 2., 4., 4., 4., 0., 2., 4., 4., 4., 2., 4., 2., 3., 2., 4.,
       2., 2., 4., 4., 4., 2., 3., 4., 1., 2., 4., 3., 4., 4., 4., 4., 4.,
       2., 3., 2., 3., 4., 1., 4., 4., 4., 2., 2., 2., 4., 4., 2., 3., 3.,
       4., 4., 4., 4., 2., 2., 4., 3., 2., 3., 4., 3., 4., 4., 1., 4., 4.,
       4., 3., 4., 4., 4., 0., 1., 4., 4., 4., 4., 4., 4., 4., 1., 4., 4.,
       4., 2., 4., 0., 4., 4., 4., 4., 4., 4., 4., 4., 4., 2., 2., 4., 4.,
       4., 4., 4., 4., 3., 4., 4., 4., 4., 4., 2., 4., 4., 4., 3., 2., 4.,
       4., 3., 4., 4., 4., 4., 0., 4., 2., 4., 4., 4., 2., 4., 4., 4., 4.,
       4., 4., 2., 4., 4., 2., 4., 4., 2., 4., 4., 2., 2., 4., 4., 2., 4.,
       4., 4., 2., 2., 3., 4., 4., 2., 2., 4., 2., 4., 2., 2., 4., 4., 2.,
       4., 2., 4., 3., 4., 2., 4., 4., 4., 3., 2., 4., 1., 3., 4., 2., 4.,
       4., 4., 2., 4., 1., 2., 2., 2., 3., 2., 4., 2., 2., 4., 4., 4., 4.,
       4., 2., 4., 4., 4., 4., 4., 2., 4., 4., 2., 3., 3., 2., 3., 4., 4.,
       2., 2., 4.])

In [92]:
from sklearn.metrics import accuracy_score 
accuracy_score(y_pred,y_test)

0.6605351170568562