In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings('ignore')

In [2]:
url=r'https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv'

In [3]:
data=pd.read_csv(url)
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [4]:
data.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [5]:
data.isnull().sum() / len(data) * 100

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            19.865320
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.000000
Cabin          77.104377
Embarked        0.224467
dtype: float64

In [6]:
data=data.drop(columns='Cabin')
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

### Fillna

In [7]:
data['Age'].value_counts()

Age
24.00    30
22.00    27
18.00    26
19.00    25
28.00    25
         ..
36.50     1
55.50     1
0.92      1
23.50     1
74.00     1
Name: count, Length: 88, dtype: int64

In [8]:
data['Age']=data['Age'].fillna(24.00)

In [9]:
data['Embarked'].value_counts()

Embarked
S    644
C    168
Q     77
Name: count, dtype: int64

In [10]:
data['Embarked']=data['Embarked'].fillna('S')

In [11]:
data.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

### Mean

In [12]:
data2=data.copy()
data2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,24.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [13]:
data2['Age'].mean()

28.566969696969696

In [14]:
data2['Age']=data2['Age'].fillna(data2['Age'].mean())

In [15]:
data2.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

### Median

In [16]:
data3=data.copy()
data3

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,24.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [17]:
data3['Age'].median()

24.0

In [18]:
data3['Age']=data3['Age'].fillna(data3['Age'].median())

In [19]:
data3.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

### Mode

In [20]:
data4=data.copy()
data4

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,24.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [21]:
data4['Age'].mode()

0    24.0
Name: Age, dtype: float64

In [22]:
data4['Age']=data4['Age'].fillna(data4['Age'].mode()[0])
data4

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,24.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [23]:
data4['Embarked'].mode()

0    S
Name: Embarked, dtype: object

In [24]:
data4['Embarked']=data4['Embarked'].fillna(data4['Embarked'].mode()[0])
data4

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,24.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [25]:
data5=data.copy()
data5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,24.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [26]:
data5=data5.fillna(method='ffill')
data5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,24.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [27]:
data6=data.copy()
data6

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,24.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [28]:
data6=data6.fillna(method='bfill')
data6

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,24.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [29]:
data5.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

In [30]:
data6.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       0
dtype: int64

### Mean, Median, Mode imputation using sklearn library

In [31]:
data=pd.read_csv(url)
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [32]:
data=data.drop(columns='Cabin')
data.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Embarked'],
      dtype='object')

In [33]:
dt1=data.copy()
dt1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [34]:
from sklearn.impute import SimpleImputer
si=SimpleImputer(strategy='mean')
si

SimpleImputer()

In [35]:
dt1['Age']=si.fit_transform(dt1[['Age']])
dt1

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,Q

In [36]:
from sklearn.impute import SimpleImputer
si=SimpleImputer(strategy='median')
si

SimpleImputer(strategy='median')

In [37]:
dt2=data.copy()
dt2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [38]:
dt2['Age']=si.fit_transform(dt1[['Age']])
dt2

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.000000,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.000000,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.000000,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.000000,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.000000,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.000000,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.000000,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,29.699118,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.000000,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.000000,0,0,370376,7.7500,Q

In [39]:
si=SimpleImputer(strategy='most_frequent')
si

SimpleImputer(strategy='most_frequent')

In [40]:
dt3=data.copy()
dt3

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [41]:
dt3['Age']=si.fit_transform(dt3[['Age']])

In [42]:
dt3.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Embarked       2
dtype: int64

# Scaling

In [43]:
data5=data.copy()
data5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [44]:
data5=data5.fillna(method='ffill')
data5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,19.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

## Decimal scaling

In [45]:
data5['Age_scaled']=data5['Age']/data5['Age'].max()
data5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Age_scaled
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,0.2750
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,0.4750
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,0.3250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,0.4375
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,0.4375
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,0.3375
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,0.2375
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,19.0,1,2,W./C. 6607,23.4500,S,0.2375
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,0.3250
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,0.4000

In [46]:
data5['Fare_scaled']=data5['Fare']/data5['Fare'].max()
data5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Age_scaled,Fare_scaled
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S,0.2750,0.014151
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C,0.4750,0.139136
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S,0.3250,0.015469
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S,0.4375,0.103644
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S,0.4375,0.015713
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S,0.3375,0.025374
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S,0.2375,0.058556
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,19.0,1,2,W./C. 6607,23.4500,S,0.2375,0.045771
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C,0.3250,0.058556
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q,0.4000,0.015127

In [47]:
from sklearn.preprocessing import MaxAbsScaler
Mas=MaxAbsScaler()
Mas

MaxAbsScaler()

In [48]:
data5[['Age','Fare']]=Mas.fit_transform(data5[['Age','Fare']])
data5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Age_scaled,Fare_scaled
0,1,0,3,"Braund, Mr. Owen Harris",male,0.2750,1,0,A/5 21171,0.014151,S,0.2750,0.014151
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0.4750,1,0,PC 17599,0.139136,C,0.4750,0.139136
2,3,1,3,"Heikkinen, Miss. Laina",female,0.3250,0,0,STON/O2. 3101282,0.015469,S,0.3250,0.015469
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0.4375,1,0,113803,0.103644,S,0.4375,0.103644
4,5,0,3,"Allen, Mr. William Henry",male,0.4375,0,0,373450,0.015713,S,0.4375,0.015713
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,0.3375,0,0,211536,0.025374,S,0.3375,0.025374
887,888,1,1,"Graham, Miss. Margaret Edith",female,0.2375,0,0,112053,0.058556,S,0.2375,0.058556
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,0.2375,1,2,W./C. 6607,0.045771,S,0.2375,0.045771
889,890,1,1,"Behr, Mr. Karl Howell",male,0.3250,0,0,111369,0.058556,C,0.3250,0.058556
890,891,0,3,"Dooley, Mr. Patrick",male,0.4000,0,0,370376,0.015127,Q,0.4000,0.015127

## Min Max scaling

In [49]:
data5['Age_scaled']=(data5['Age']-data5['Age'].min())/(data5['Age'].max()-data5['Age'].min())
data5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Age_scaled,Fare_scaled
0,1,0,3,"Braund, Mr. Owen Harris",male,0.2750,1,0,A/5 21171,0.014151,S,0.271174,0.014151
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0.4750,1,0,PC 17599,0.139136,C,0.472229,0.139136
2,3,1,3,"Heikkinen, Miss. Laina",female,0.3250,0,0,STON/O2. 3101282,0.015469,S,0.321438,0.015469
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0.4375,1,0,113803,0.103644,S,0.434531,0.103644
4,5,0,3,"Allen, Mr. William Henry",male,0.4375,0,0,373450,0.015713,S,0.434531,0.015713
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,0.3375,0,0,211536,0.025374,S,0.334004,0.025374
887,888,1,1,"Graham, Miss. Margaret Edith",female,0.2375,0,0,112053,0.058556,S,0.233476,0.058556
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,0.2375,1,2,W./C. 6607,0.045771,S,0.233476,0.045771
889,890,1,1,"Behr, Mr. Karl Howell",male,0.3250,0,0,111369,0.058556,C,0.321438,0.058556
890,891,0,3,"Dooley, Mr. Patrick",male,0.4000,0,0,370376,0.015127,Q,0.396833,0.015127

In [50]:
data5['Fare_scaled']=(data5['Fare']-data5['Fare'].min())/(data5['Fare'].max()-data5['Fare'].min())
data5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Age_scaled,Fare_scaled
0,1,0,3,"Braund, Mr. Owen Harris",male,0.2750,1,0,A/5 21171,0.014151,S,0.271174,0.014151
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0.4750,1,0,PC 17599,0.139136,C,0.472229,0.139136
2,3,1,3,"Heikkinen, Miss. Laina",female,0.3250,0,0,STON/O2. 3101282,0.015469,S,0.321438,0.015469
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0.4375,1,0,113803,0.103644,S,0.434531,0.103644
4,5,0,3,"Allen, Mr. William Henry",male,0.4375,0,0,373450,0.015713,S,0.434531,0.015713
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,0.3375,0,0,211536,0.025374,S,0.334004,0.025374
887,888,1,1,"Graham, Miss. Margaret Edith",female,0.2375,0,0,112053,0.058556,S,0.233476,0.058556
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,0.2375,1,2,W./C. 6607,0.045771,S,0.233476,0.045771
889,890,1,1,"Behr, Mr. Karl Howell",male,0.3250,0,0,111369,0.058556,C,0.321438,0.058556
890,891,0,3,"Dooley, Mr. Patrick",male,0.4000,0,0,370376,0.015127,Q,0.396833,0.015127

In [51]:
from sklearn.preprocessing import MinMaxScaler
MMs=MinMaxScaler()
MMs

MinMaxScaler()

In [52]:
data5[['Age','Fare']]=MMs.fit_transform(data[['Age','Fare']])
data5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Age_scaled,Fare_scaled
0,1,0,3,"Braund, Mr. Owen Harris",male,0.271174,1,0,A/5 21171,0.014151,S,0.271174,0.014151
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0.472229,1,0,PC 17599,0.139136,C,0.472229,0.139136
2,3,1,3,"Heikkinen, Miss. Laina",female,0.321438,0,0,STON/O2. 3101282,0.015469,S,0.321438,0.015469
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0.434531,1,0,113803,0.103644,S,0.434531,0.103644
4,5,0,3,"Allen, Mr. William Henry",male,0.434531,0,0,373450,0.015713,S,0.434531,0.015713
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,0.334004,0,0,211536,0.025374,S,0.334004,0.025374
887,888,1,1,"Graham, Miss. Margaret Edith",female,0.233476,0,0,112053,0.058556,S,0.233476,0.058556
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,0.045771,S,0.233476,0.045771
889,890,1,1,"Behr, Mr. Karl Howell",male,0.321438,0,0,111369,0.058556,C,0.321438,0.058556
890,891,0,3,"Dooley, Mr. Patrick",male,0.396833,0,0,370376,0.015127,Q,0.396833,0.015127

## Standard scaling

In [53]:
data5['Age_scaled']=(data5['Age'] - data5['Age'].mean()) / data5['Age'].std()
data5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Age_scaled,Fare_scaled
0,1,0,3,"Braund, Mr. Owen Harris",male,0.271174,1,0,A/5 21171,0.014151,S,-0.530005,0.014151
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0.472229,1,0,PC 17599,0.139136,C,0.571430,0.139136
2,3,1,3,"Heikkinen, Miss. Laina",female,0.321438,0,0,STON/O2. 3101282,0.015469,S,-0.254646,0.015469
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0.434531,1,0,113803,0.103644,S,0.364911,0.103644
4,5,0,3,"Allen, Mr. William Henry",male,0.434531,0,0,373450,0.015713,S,0.364911,0.015713
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,0.334004,0,0,211536,0.025374,S,-0.185807,0.025374
887,888,1,1,"Graham, Miss. Margaret Edith",female,0.233476,0,0,112053,0.058556,S,-0.736524,0.058556
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,0.045771,S,NaN,0.045771
889,890,1,1,"Behr, Mr. Karl Howell",male,0.321438,0,0,111369,0.058556,C,-0.254646,0.058556
890,891,0,3,"Dooley, Mr. Patrick",male,0.396833,0,0,370376,0.015127,Q,0.158392,0.015127

In [54]:
data5['Fare_scaled']=(data5['Fare'] - data['Fare'].mean()) / data['Fare'].std()
data5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Age_scaled,Fare_scaled
0,1,0,3,"Braund, Mr. Owen Harris",male,0.271174,1,0,A/5 21171,0.014151,S,-0.530005,-0.647773
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0.472229,1,0,PC 17599,0.139136,C,0.571430,-0.645258
2,3,1,3,"Heikkinen, Miss. Laina",female,0.321438,0,0,STON/O2. 3101282,0.015469,S,-0.254646,-0.647746
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0.434531,1,0,113803,0.103644,S,0.364911,-0.645972
4,5,0,3,"Allen, Mr. William Henry",male,0.434531,0,0,373450,0.015713,S,0.364911,-0.647741
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,0.334004,0,0,211536,0.025374,S,-0.185807,-0.647547
887,888,1,1,"Graham, Miss. Margaret Edith",female,0.233476,0,0,112053,0.058556,S,-0.736524,-0.646879
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,0.045771,S,NaN,-0.647137
889,890,1,1,"Behr, Mr. Karl Howell",male,0.321438,0,0,111369,0.058556,C,-0.254646,-0.646879
890,891,0,3,"Dooley, Mr. Patrick",male,0.396833,0,0,370376,0.015127,Q,0.158392,-0.647753

In [55]:
from sklearn.preprocessing import StandardScaler
SS=StandardScaler()
SS

StandardScaler()

In [56]:
data5[['Age','Fare']]=SS.fit_transform(data[['Age','Fare']])
data5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Age_scaled,Fare_scaled
0,1,0,3,"Braund, Mr. Owen Harris",male,-0.530377,1,0,A/5 21171,-0.502445,S,-0.530005,-0.647773
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0.571831,1,0,PC 17599,0.786845,C,0.571430,-0.645258
2,3,1,3,"Heikkinen, Miss. Laina",female,-0.254825,0,0,STON/O2. 3101282,-0.488854,S,-0.254646,-0.647746
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0.365167,1,0,113803,0.420730,S,0.364911,-0.645972
4,5,0,3,"Allen, Mr. William Henry",male,0.365167,0,0,373450,-0.486337,S,0.364911,-0.647741
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,-0.185937,0,0,211536,-0.386671,S,-0.185807,-0.647547
887,888,1,1,"Graham, Miss. Margaret Edith",female,-0.737041,0,0,112053,-0.044381,S,-0.736524,-0.646879
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,-0.176263,S,NaN,-0.647137
889,890,1,1,"Behr, Mr. Karl Howell",male,-0.254825,0,0,111369,-0.044381,C,-0.254646,-0.646879
890,891,0,3,"Dooley, Mr. Patrick",male,0.158503,0,0,370376,-0.492378,Q,0.158392,-0.647753

## Robust scaling

In [57]:
data5['Age_scaled']=(data5['Age']-data5['Age'].quantile(.25)) / (data5['Age'].quantile(.75) - data5['Age'].quantile(.25))
data5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Age_scaled,Fare_scaled
0,1,0,3,"Braund, Mr. Owen Harris",male,-0.530377,1,0,A/5 21171,-0.502445,S,0.104895,-0.647773
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0.571831,1,0,PC 17599,0.786845,C,1.000000,-0.645258
2,3,1,3,"Heikkinen, Miss. Laina",female,-0.254825,0,0,STON/O2. 3101282,-0.488854,S,0.328671,-0.647746
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0.365167,1,0,113803,0.420730,S,0.832168,-0.645972
4,5,0,3,"Allen, Mr. William Henry",male,0.365167,0,0,373450,-0.486337,S,0.832168,-0.647741
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,-0.185937,0,0,211536,-0.386671,S,0.384615,-0.647547
887,888,1,1,"Graham, Miss. Margaret Edith",female,-0.737041,0,0,112053,-0.044381,S,-0.062937,-0.646879
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,-0.176263,S,NaN,-0.647137
889,890,1,1,"Behr, Mr. Karl Howell",male,-0.254825,0,0,111369,-0.044381,C,0.328671,-0.646879
890,891,0,3,"Dooley, Mr. Patrick",male,0.158503,0,0,370376,-0.492378,Q,0.664336,-0.647753

In [58]:
data5['Fare_scaled']=(data5['Fare']-data5['Fare'].quantile(.25)) / (data5['Fare'].quantile(.75) - data5['Fare'].quantile(.25))
data5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Age_scaled,Fare_scaled
0,1,0,3,"Braund, Mr. Owen Harris",male,-0.530377,1,0,A/5 21171,-0.502445,S,0.104895,-0.028602
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0.571831,1,0,PC 17599,0.786845,C,1.000000,2.744651
2,3,1,3,"Heikkinen, Miss. Laina",female,-0.254825,0,0,STON/O2. 3101282,-0.488854,S,0.328671,0.000632
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0.365167,1,0,113803,0.420730,S,0.832168,1.957141
4,5,0,3,"Allen, Mr. William Henry",male,0.365167,0,0,373450,-0.486337,S,0.832168,0.006046
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,-0.185937,0,0,211536,-0.386671,S,0.384615,0.220428
887,888,1,1,"Graham, Miss. Margaret Edith",female,-0.737041,0,0,112053,-0.044381,S,-0.062937,0.956690
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,-0.176263,S,NaN,0.673013
889,890,1,1,"Behr, Mr. Karl Howell",male,-0.254825,0,0,111369,-0.044381,C,0.328671,0.956690
890,891,0,3,"Dooley, Mr. Patrick",male,0.158503,0,0,370376,-0.492378,Q,0.664336,-0.006947

In [59]:
from sklearn.preprocessing import RobustScaler
RS=RobustScaler()
RS

RobustScaler()

In [60]:
data5[['Age','Fare']]=RS.fit_transform(data5[['Age','Fare']])
data5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked,Age_scaled,Fare_scaled
0,1,0,3,"Braund, Mr. Owen Harris",male,-0.335664,1,0,A/5 21171,-0.312011,S,0.104895,-0.028602
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0.559441,1,0,PC 17599,2.461242,C,1.000000,2.744651
2,3,1,3,"Heikkinen, Miss. Laina",female,-0.111888,0,0,STON/O2. 3101282,-0.282777,S,0.328671,0.000632
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0.391608,1,0,113803,1.673732,S,0.832168,1.957141
4,5,0,3,"Allen, Mr. William Henry",male,0.391608,0,0,373450,-0.277363,S,0.832168,0.006046
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,-0.055944,0,0,211536,-0.062981,S,0.384615,0.220428
887,888,1,1,"Graham, Miss. Margaret Edith",female,-0.503497,0,0,112053,0.673281,S,-0.062937,0.956690
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,0.389604,S,NaN,0.673013
889,890,1,1,"Behr, Mr. Karl Howell",male,-0.111888,0,0,111369,0.673281,C,0.328671,0.956690
890,891,0,3,"Dooley, Mr. Patrick",male,0.223776,0,0,370376,-0.290356,Q,0.664336,-0.006947

# Feature Encoding

In [94]:
data5=data.copy()
data5.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S

In [95]:
data5=data5.fillna(method='ffill')
data5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,19.0,1,2,W./C. 6607,23.4500,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,Q

In [96]:
from sklearn.preprocessing import RobustScaler
RS=RobustScaler()
RS

RobustScaler()

In [97]:
data5[['Age','Fare']]=RS.fit_transform(data5[['Age','Fare']])
data5

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,-0.333333,1,0,A/5 21171,-0.312011,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,0.555556,1,0,PC 17599,2.461242,C
2,3,1,3,"Heikkinen, Miss. Laina",female,-0.111111,0,0,STON/O2. 3101282,-0.282777,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,0.388889,1,0,113803,1.673732,S
4,5,0,3,"Allen, Mr. William Henry",male,0.388889,0,0,373450,-0.277363,S
...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,-0.055556,0,0,211536,-0.062981,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,-0.500000,0,0,112053,0.673281,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,-0.500000,1,2,W./C. 6607,0.389604,S
889,890,1,1,"Behr, Mr. Karl Howell",male,-0.111111,0,0,111369,0.673281,C
890,891,0,3,"Dooley, Mr. Patrick",male,0.222222,0,0,370376,-0.290356,Q

In [98]:
data5=data5.drop(columns=['Name','Ticket'])
data5

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,male,-0.333333,1,0,-0.312011,S
1,2,1,1,female,0.555556,1,0,2.461242,C
2,3,1,3,female,-0.111111,0,0,-0.282777,S
3,4,1,1,female,0.388889,1,0,1.673732,S
4,5,0,3,male,0.388889,0,0,-0.277363,S
...,...,...,...,...,...,...,...,...,...
886,887,0,2,male,-0.055556,0,0,-0.062981,S
887,888,1,1,female,-0.500000,0,0,0.673281,S
888,889,0,3,female,-0.500000,1,2,0.389604,S
889,890,1,1,male,-0.111111,0,0,0.673281,C
890,891,0,3,male,0.222222,0,0,-0.290356,Q

In [99]:
data5=pd.get_dummies(data5,dtype='int',drop_first=True)

In [111]:
data5

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S
0,1,0,3,-0.333333,1,0,-0.312011,1,0,1
1,2,1,1,0.555556,1,0,2.461242,0,0,0
2,3,1,3,-0.111111,0,0,-0.282777,0,0,1
3,4,1,1,0.388889,1,0,1.673732,0,0,1
4,5,0,3,0.388889,0,0,-0.277363,1,0,1
...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,-0.055556,0,0,-0.062981,1,0,1
887,888,1,1,-0.500000,0,0,0.673281,0,0,1
888,889,0,3,-0.500000,1,2,0.389604,0,0,1
889,890,1,1,-0.111111,0,0,0.673281,1,0,0
890,891,0,3,0.222222,0,0,-0.290356,1,1,0

In [100]:
X=data5.drop(columns='Survived')

In [101]:
y=data5['Survived']

In [102]:
from sklearn.model_selection import train_test_split

In [103]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [104]:
X_train

,PassengerId,Pclass,Age,SibSp,Parch,Fare,Sex_male,Embarked_Q,Embarked_S
331,332,1,0.972222,0,0,0.608317,1,0,1
733,734,2,-0.277778,0,0,-0.062981,1,0,1
382,383,3,0.222222,0,0,-0.282777,1,0,1
704,705,3,-0.111111,1,0,-0.285843,1,0,1
813,814,3,-1.222222,4,2,0.728501,0,0,1
...,...,...,...,...,...,...,...,...,...
106,107,3,-0.388889,0,0,-0.294687,0,0,1
270,271,1,0.388889,0,0,0.716591,1,0,1
860,861,3,0.722222,2,0,-0.014981,1,0,1
435,436,1,-0.777778,1,2,4.571140,0,0,1
102,103,1,-0.388889,0,1,2.721281,1,0,1

In [105]:
from sklearn.linear_model import LogisticRegression
lr=LogisticRegression()
lr

LogisticRegression()

In [106]:
lr.fit(X_train,y_train)

LogisticRegression()

In [107]:
y_pred=lr.predict(X_test)

In [108]:
from sklearn.metrics import accuracy_score
accuracy_score(y_pred,y_test)

0.776536312849162

In [109]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_pred,y_test)

array([[89, 24],
       [16, 50]], dtype=int64)

In [110]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.79      0.85      0.82       105
           1       0.76      0.68      0.71        74

    accuracy                           0.78       179
   macro avg       0.77      0.76      0.77       179
weighted avg       0.78      0.78      0.77       179